In [1]:
from IPython.display import display, HTML
display(HTML("""
<style>
div.container{width:86% !important;}
div.cell.code_cell.rendered{width:100%;}
div.CodeMirror {font-family:Consolas; font-size:15pt;}
div.output {font-size:15pt; font-weight:bold;}
div.input {font-family:Consolas; font-size:15pt;}
div.prompt {min-width:70px;}
div#toc-wrapper{padding-top:120px;}
div.text_cell_render ul li{font-size:12pt;padding:5px;}
table.dataframe{font-size:15px;}
</style>
"""))

<font color="red" size="5">ch010 N차원 배열 다루기</font>
- [numpy](https://numpy.org/doc/stable/)
- [numpy API](https://numpy.org/doc/stable/reference/index.html)
- N차원 배열 객체
- 2차원 배열은 행렬개념
- numpy패키지는 C언어로 구현되어 고성능 수치 계산 패키지
# 1절 넘파이 패키지

In [5]:
import numpy as np
np.__version__

'1.23.5'

In [7]:
#np.arange(from, stop, step) : from부터 stop앞까지 step씩 증감한 정수값을 배열로 생성
a = np.arange(15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

# 1.1 배열 속성

In [10]:
from numpy import arange
a = arange(15).reshape(3,5) #3행 5열짜리 2차뭔 배열로 return
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [11]:
type(a) #a변수의 타입

numpy.ndarray

In [12]:
a.dtype #a배열 요소의 타입

dtype('int32')

In [13]:
a.dtype.name

'int32'

In [14]:
a.itemsize #한 요소의 bytesize

4

In [15]:
a.ndim #차원수(축수)

2

In [16]:
a.size # 배열 요소의 갯수

15

In [17]:
a.shape #배열의 구조(튜플)

(3, 5)

## 1.2 배열 변경(구조, 타입)

In [18]:
print('구조변경 전', a, sep='\n')
a.shape = (5, 3)
print('구조변경 후', a, sep='\n')

구조변경 전
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
구조변경 후
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [19]:
# 타입변경(x)
a= arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [20]:
a.dtype

dtype('int32')

In [22]:
a.itemsize

4

In [23]:
a.dtype = np.int64
a.dtype

dtype('int64')

In [25]:
a.itemsize

8

In [26]:
a.size, a.shape

(6, (3, 2))

In [27]:
a

array([[ 4294967296, 12884901890],
       [21474836484, 30064771078],
       [38654705672, 47244640266]], dtype=int64)

In [50]:
# 타입변경(O)
a= arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [51]:
a = a.astype(np.int64) #a.astype('int64')와 같음.
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]], dtype=int64)

In [52]:
a.dtype

dtype('int64')

In [53]:
a.itemsize

8

In [54]:
a.size, a.shape

(12, (3, 4))

In [55]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]], dtype=int64)

In [56]:
a.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11], dtype=int64)

In [57]:
a.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11], dtype=int64)

## 1.3 배열 저장

In [71]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]], dtype=int64)

In [74]:
import pickle
with open('data/ch10_a.pkl', 'wb') as f:
    pickle.dump(a,f)

FileNotFoundError: [Errno 2] No such file or directory: 'data/ch10_a.pkl'

In [67]:
with open('data/ch10_a.pkl', 'rb') as f:
    load_a = pickle.load(f)

FileNotFoundError: [Errno 2] No such file or directory: 'data/ch10_a.pkl'

In [68]:
load_a

NameError: name 'load_a' is not defined

In [69]:
np.all(a == load_a)

NameError: name 'load_a' is not defined

In [70]:
np.save('data/ch10_a.npy',a)

FileNotFoundError: [Errno 2] No such file or directory: 'data/ch10_a.npy'

In [73]:
load _a2 = np.load('data/ch10_a.npy')
np.all(load_a2==a)

SyntaxError: invalid syntax (3664472808.py, line 1)

# 2절. 넘파이 배열
- array()함수 : 다른 파이썬 데이터 구조를 배열로 변환
- arange(), ones(), zeros()